product: jvm/app

test-settings:
  jvm:
    test:
      freeJvmArgs: ["-Xshare:off", "-XX:+EnableDynamicAgentLoading"]

dependencies:
  - $libs.jackson

test-dependencies:
  - $libs.kotest.assertions
  - $libs.kotest.framework
  - $libs.kotest.runner: runtime-only
  - $libs.mockk
